spring.application.name=backend
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_management
spring.datasource.username=postgres
spring.datasource.password=abc123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=defaultSecretKeyForDev0123456789012345678901234567890
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

#Cloudinary
cloudinary.cloud-name=depkihkr7
cloudinary.api-key=913671594932787
cloudinary.api-secret=SRxAujzAcPRi5_dJrBaySXsQ56U
app.image.max-count-per-room=10

# CORS
app.cors.allowed-origins=http://localhost:5173
