spring.application.name=backend
server.port=8080

# Kết nối đúng vào Database Lan Anh đã tạo trong pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/QLKhachSan
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA - Đổi từ validate sang update để không bị lỗi cấu trúc
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT - Điền tạm một chuỗi bí mật
app.jwt.secret=LanAnhSecretKeyForHotelManagement2026
app.jwt.expiration=86400000
app.jwt.refresh-expiration=604800000

# CORS - Cho phép cổng React của nhóm truy cập
app.cors.allowed-origins=http://localhost:5173